# Generated by Django 5.2.16 on 2026-07-29 08:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('supervisor', 'Supervisor'), ('admin', 'Administrator')], max_length=20)),
                ('focus_area', models.TextField(blank=True, default='')),
                ('profile_url', models.URLField(blank=True, default='', max_length=500)),
                ('locale', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_case_insensitive_unique')],
            },
        ),
    ]
