# Generated by Django 5.2.16 on 2026-07-29 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login', 'Sign-in link'), ('invitation', 'Invitation'), ('registration_confirmed', 'Registration confirmed'), ('registration_cancelled', 'Registration cancelled'), ('reminder', 'Reminder'), ('session_cancelled', 'Session cancelled'), ('session_changed', 'Session changed'), ('session_created', 'Session created')], max_length=32)),
                ('sent_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'kind', 'sent_at'], name='supervision_user_id_d1e2cc_idx')],
            },
        ),
    ]
