# Generated by Django 5.2.16 on 2026-07-29 16:03

import django.db.models.deletion
import supervision.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_logintoken_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_url', models.URLField(blank=True, default='', max_length=500)),
                ('default_duration_minutes', models.PositiveIntegerField(default=90)),
                ('default_capacity', models.PositiveIntegerField(default=5)),
                ('weekly_session_cap', models.PositiveIntegerField(default=2)),
                ('enforce_weekly_cap', models.BooleanField(default=True)),
                ('reminder_lead_hours', models.PositiveIntegerField(default=24)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In person')], max_length=20)),
                ('room', models.CharField(blank=True, default='', max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('cancelled', 'Cancelled')], default='offered', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('took_place', models.BooleanField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_uid', models.CharField(default=supervision.models.generate_calendar_uid, max_length=200, unique=True)),
                ('calendar_sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_cancelled', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_held', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='supervision.session'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date', 'status'], name='supervision_date_187d11_idx'),
        ),
    ]
