# Generated by Django 5.2.16 on 2026-07-30 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_settings_session_emaillog_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('self_signup', 'Signed up themselves'), ('added_at_confirmation', 'Added when the session was reviewed')], default='self_signup', max_length=32)),
                ('created_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('attendance_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('attendance_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='supervision.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('session', 'user'), name='one_active_registration_per_person_per_session')],
            },
        ),
    ]
