# Generated by Django 5.2.16 on 2026-08-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='enforce_weekly_cap',
        ),
    ]
